#!/usr/bin/python
# -*- coding: utf-8 -*-
'''
    This file was extracted from wikipedia by Gabriel Fonseca. The countries here are countries that issue/issued the given currency and not countries that use them.
'''
fallback = {
'AED': {'countries': 'United Arab Emirates', 'symbol': 'د.إ'},
'AFN': {'countries': 'Afghanistan', 'symbol':'؋'},
'ALL': {'countries': 'Albania', 'symbol':'L'},
'AMD': {'countries': 'Armenia', 'symbol':'֏'},
'ANG': {'countries': 'Curaçao (CW),  Sint Maarten (SX)', 'symbol':'NAƒ'},
'AOA': {'countries': 'Angola', 'symbol':'Kz'},
'ARS': {'countries': 'Argentina', 'symbol':'$'},
'AUD': {'countries': 'Australia', 'symbol':'$, A$, AU$'},
'AWG': {'countries': 'Aruba', 'symbol':'Afl'},
'AZN': {'countries': 'Azerbaijan', 'symbol':'₼'},
'BAM': {'countries': 'Bosnia and Herzegovina', 'symbol':'KM'},
'BBD': {'countries': 'Barbados', 'symbol':'$, Bds$'},
'BDT': {'countries': 'Bangladesh', 'symbol':'৳'},
'BGN': {'countries': 'Bulgaria', 'symbol':'лв'},
'BHD': {'countries': 'Bahrain', 'symbol':'.د.ب (Arabic) or BD (Latin)'},
'BIF': {'countries': 'Burundi', 'symbol':'FBu'},
'BMD': {'countries': 'Bermuda', 'symbol':'$'},
'BND': {'countries': 'Brunei', 'symbol':'$, B$'},
'BOB': {'countries': 'Bolivia', 'symbol':'Bs'},
'BOV': {'countries': 'Bolivia', 'symbol':''},
'BRL': {'countries': 'Brazil', 'symbol':'$, B$'},
'BSD': {'countries': 'Bahamas', 'symbol':'$, B$'},
'BTN': {'countries': 'Bhutan', 'symbol':'Nu.'},
'BWP': {'countries': 'Botswana', 'symbol':'P'},
'BYN': {'countries': 'Belarus', 'symbol':'Br'},
'BZD': {'countries': 'Belize', 'symbol':'$'},
'CAD': {'countries': 'Canada', 'symbol':'$, Can$, C$, CA$ or CAD'},
'CDF': {'countries': 'Democratic Republic of the Congo', 'symbol':'FC'},
'CHE': {'countries': 'Switzerland', 'symbol':''},
'CHF': {'countries': 'Switzerland', 'symbol':'CHF'},
'CHW': {'countries': 'Switzerland', 'symbol':''},
'CLF': {'countries': 'Chile', 'symbol':'UF'},
'CLP': {'countries': 'Chile', 'symbol':'$'},
'CNY': {'countries': 'China', 'symbol':'元 / ¥'},
'COP': {'countries': 'Colombia', 'symbol':'$'},
'COU': {'countries': 'Colombia', 'symbol':'UVR'},
'CRC': {'countries': 'Costa Rica', 'symbol':'₡'},
'CUC': {'countries': 'Cuba', 'symbol':'$, CUC or CUC$'},
'CUP': {'countries': 'Cuba', 'symbol':'$, $MN, or ₱'},
'CVE': {'countries': 'Cabo Verde', 'symbol':'$'},
'CZK': {'countries': 'Czechia', 'symbol':'Kč'},
'DJF': {'countries': 'Djibouti', 'symbol':'Fdj'},
'DKK': {'countries': 'Denmark', 'symbol':'kroner'},
'DOP': {'countries': 'Dominican Republic', 'symbol':'$ or RD$'},
'DZD': {'countries': 'Algeria', 'symbol':'دج (Arabic) or DA (Latin)'},
'EGP': {'countries': 'Egypt', 'symbol':'E£ or ج.م or L.E'},
'ERN': {'countries': 'Eritrea', 'symbol':'Nkf (Latin script) ናቕፋ (Ge\'ez script)ناكفا (Arabic script)'},
'ETB': {'countries': 'Ethiopia', 'symbol':'Br (Latin Script) ብር (Ethiopic Script)'},
'EUR': {'countries': 'European Union (EU)', 'symbol':'€'},
'FJD': {'countries': 'Fiji', 'symbol':'	FJ$ or FJD'},
'FKP': {'countries': 'Falkland Islands (pegged to GBP 1:1)', 'symbol':'	£'},
'GBP': {'countries': 'United Kingdom', 'symbol':'	£'},
'GEL': {'countries': 'Georgia', 'symbol':'₾ (Sign of Georgian Lari.svg), ლ, GEL'},
'GHS': {'countries': 'Ghana', 'symbol':'GH₵ (Also often GH¢)'},
'GIP': {'countries': 'Gibraltar (pegged to GBP 1:1)', 'symbol':'£'},
'GMD': {'countries': 'Gambia', 'symbol':'D'},
'GNF': {'countries': 'Guinea', 'symbol':'FG (possibly also Fr or GFr)'},
'GTQ': {'countries': 'Guatemala', 'symbol':'Q'},
'GYD': {'countries': 'Guyana', 'symbol':'$, G$ and GY$'},
'HKD': {'countries': 'Hong Kong', 'symbol':'"$", "HK$" or "元"'},
'HNL': {'countries': 'Honduras', 'symbol':'L'},
'HRK': {'countries': 'Croatia', 'symbol':'kn'},
'HTG': {'countries': 'Haiti', 'symbol':'G'},
'HUF': {'countries': 'Hungary', 'symbol':'Ft'},
'IDR': {'countries': 'Indonesia', 'symbol':'Rp'},
'ILS': {'countries': 'Israel', 'symbol':'₪'},
'INR': {'countries': 'India,  Bhutan', 'symbol':'₹'},
'IQD': {'countries': 'Iraq', 'symbol':'د.ع'},
'IRR': {'countries': 'Iran', 'symbol':'﷼'},
'ISK': {'countries': 'Iceland', 'symbol':'kr'},
'JMD': {'countries': 'Jamaica', 'symbol':'$'},
'JOD': {'countries': 'Jordan', 'symbol':'د.أ'},
'JPY': {'countries': 'Japan', 'symbol':'¥ (international), 円 (Japan—present day), 圓 (Japan—traditional)'},
'KES': {'countries': 'Kenya', 'symbol':'KSh, /=, /-, K'},
'KGS': {'countries': 'Kyrgyzstan', 'symbol':'Лв'},
'KHR': {'countries': 'Cambodia', 'symbol':'៛'},
'KMF': {'countries': 'Comoros', 'symbol':'CF'},
'KPW': {'countries': 'North Korea', 'symbol':'₩'},
'KRW': {'countries': 'South Korea', 'symbol':'₩'},
'KWD': {'countries': 'Kuwait', 'symbol':'د.ك or KD'},
'KYD': {'countries': 'Cayman Islands', 'symbol':'$'},
'KZT': {'countries': 'Kazakhstan', 'symbol':'₸'},
'LAK': {'countries': 'Laos', 'symbol':'₭ or ₭N'},
'LBP': {'countries': 'Lebanon', 'symbol':'ل.ل.‎, LL (international)'},
'LKR': {'countries': 'Sri Lanka', 'symbol':'Rs, රු'},
'LRD': {'countries': 'Liberia', 'symbol':'$, L$, LD$'},
'LSL': {'countries': 'Lesotho', 'symbol':'L or M (pl.)'},
'LYD': {'countries': 'Libya', 'symbol':'LD and ل.د'},
'MAD': {'countries': 'Morocco,  Western Sahara', 'symbol':'DH'},
'MDL': {'countries': 'Moldova', 'symbol':'L'},
'MGA': {'countries': 'Madagascar', 'symbol':'Ar'},
'MKD': {'countries': 'North Macedonia', 'symbol':'den / ден'},
'MMK': {'countries': 'Myanmar', 'symbol':'K'},
'MNT': {'countries': 'Mongolia', 'symbol':'₮'},
'MOP': {'countries': 'Macau', 'symbol':'MOP$'},
'MRU': {'countries': 'Mauritania', 'symbol':'UM'},
'MUR': {'countries': 'Mauritius', 'symbol':'Rs'},
'MVR': {'countries': 'Maldives', 'symbol':'Rf, MRf, MVR, .ރ or /-'},
'MWK': {'countries': 'Malawi', 'symbol':'K'},
'MXN': {'countries': 'Mexico', 'symbol':'$ or Mex$'},
'MXV': {'countries': 'Mexico', 'symbol':''},
'MYR': {'countries': 'Malaysia', 'symbol':'RM'},
'MZN': {'countries': 'Mozambique', 'symbol':'MT, MTn'},
'NAD': {'countries': 'Namibia', 'symbol':'$, N$'},
'NGN': {'countries': 'Nigeria', 'symbol':'₦'},
'NIO': {'countries': 'Nicaragua', 'symbol':'C$'},
'NOK': {'countries': 'Norway', 'symbol':'kr'},
'NPR': {'countries': 'Nepal', 'symbol':'रू'},
'NZD': {'countries': 'New Zealand', 'symbol':'$, NZ$'},
'OMR': {'countries': 'Oman', 'symbol':'ر.ع. ; R.O'},
'PAB': {'countries': 'Panama', 'symbol':'B/.'},
'PEN': {'countries': 'Peru', 'symbol':'S/'},
'PGK': {'countries': 'Papua New Guinea', 'symbol':'K'},
'PHP': {'countries': 'Philippines', 'symbol':'₱'},
'PKR': {'countries': 'Pakistan', 'symbol':'₨'},
'PLN': {'countries': 'Poland', 'symbol':'zł'},
'PYG': {'countries': 'Paraguay', 'symbol':'₲'},
'QAR': {'countries': 'Qatar', 'symbol':'QR or ر.ق'},
'RON': {'countries': 'Romania', 'symbol':'L'},
'RSD': {'countries': 'Serbia', 'symbol':'din / дин'},
'RUB': {'countries': 'Russia', 'symbol':'₽'},
'RWF': {'countries': 'Rwanda', 'symbol':'FRw, RF, R₣'},
'SAR': {'countries': 'Saudi Arabia', 'symbol':'SAR, ر.س or ﷼'},
'SBD': {'countries': 'Solomon Islands', 'symbol':'$, SI$'},
'SCR': {'countries': 'Seychelles', 'symbol':'SCR or SR'},
'SDG': {'countries': 'Sudan', 'symbol':'SDG, £SD or ج.س'},
'SEK': {'countries': 'Sweden', 'symbol':'kr'},
'SGD': {'countries': 'Singapore', 'symbol':'S$ or $'},
'SHP': {'countries': 'Saint Helena', 'symbol':'£'},
'SLL': {'countries': 'Sierra Leone', 'symbol':'Le'},
'SOS': {'countries': 'Somalia', 'symbol':'Sh.So'},
'SRD': {'countries': 'Suriname', 'symbol':'$'},
'SSP': {'countries': 'South Sudan', 'symbol':'SS£'},
'STN': {'countries': 'São Tomé and Príncipe', 'symbol':'Db'},
'SVC': {'countries': 'El Salvador', 'symbol':'₡'},
'SYP': {'countries': 'Syria', 'symbol':'LS or £S'},
'SZL': {'countries': 'Eswatini', 'symbol':'L or E (pl.)'},
'THB': {'countries': 'Thailand', 'symbol':'฿'},
'TJS': {'countries': 'Tajikistan', 'symbol':'SM'},
'TMT': {'countries': 'Turkmenistan', 'symbol':'T'},
'TND': {'countries': 'Tunisia', 'symbol':'د.ت (Tunisian Arabic) or DT (Latin)'},
'TOP': {'countries': 'Tonga', 'symbol':'T$ (sometimes PT)'},
'TRY': {'countries': 'Turkey', 'symbol':'Lira: ₺, TLKuruş: kr'},
'TTD': {'countries': 'Trinidad and Tobago', 'symbol':'$ or TT$'},
'TWD': {'countries': 'Taiwan', 'symbol':'NT$, 圓, $'},
'TZS': {'countries': 'Tanzania', 'symbol':'TSh'},
'UAH': {'countries': 'Ukraine', 'symbol':'₴ or грн'},
'UGX': {'countries': 'Uganda', 'symbol':'USh'},
'USD': {'countries': 'United States', 'symbol':'$'},
'USN': {'countries': 'United States', 'symbol':'$'},
'UYI': {'countries': 'Uruguay', 'symbol':''},
'UYU': {'countries': 'Uruguay', 'symbol':'$ or $U'},
'UYW': {'countries': 'Uruguay', 'symbol':''},
'UZS': {'countries': 'Uzbekistan', 'symbol':'soʻm'},
'VES': {'countries': 'Venezuela', 'symbol':'Bs.S. or Bs'},
'VND': {'countries': 'Vietnam', 'symbol':'₫/đ'},
'VUV': {'countries': 'Vanuatu', 'symbol':'VT'},
'WST': {'countries': 'Samoa', 'symbol':'WS$'},
'XAF': {'countries': 'Cameroon (CM),  Central African Republic (CF),  Republic of the Congo (CG),  Chad (TD),  Equatorial Guinea (GQ),  Gabon (GA)', 'symbol':'FCFA'},
'XAG': {'countries': '', 'symbol':''},
'XAU': {'countries': '', 'symbol':''},
'XBA': {'countries': '', 'symbol':''},
'XBB': {'countries': '', 'symbol':''},
'XBC': {'countries': '', 'symbol':''},
'XBD': {'countries': '', 'symbol':''},
'XCD': {'countries': 'Anguilla (AI),  Antigua and Barbuda (AG),  Dominica (DM),  Grenada (GD),  Montserrat (MS),  Saint Kitts and Nevis (KN),  Saint Lucia (LC),  Saint Vincent and the Grenadines (VC)', 'symbol':''},
'XDR': {'countries': 'International Monetary Fund', 'symbol':''},
'XOF': {'countries': 'Ivoire (CI),  Guinea-Bissau (GW),  Mali (ML),  Niger (NE),  Senegal (SN),  Togo (TG)', 'symbol':''},
'XPD': {'countries': '', 'symbol':''},
'XPF': {'countries': 'French territories of the Pacific Ocean:  French Polynesia (PF),  New Caledonia (NC),  Wallis and Futuna (WF)', 'symbol':''},
'XPT': {'countries': '', 'symbol':''},
'XSU': {'countries': 'Unified System for Regional Compensation (SUCRE)', 'symbol':'Sucre'},
'XTS': {'countries': '', 'symbol':''},
'XUA': {'countries': 'African Development Bank', 'symbol':''},
'XXX': {'countries': '', 'symbol':''},
'YER': {'countries': 'Yemen', 'symbol':'ر.ي'},
'ZAR': {'countries': 'Lesotho,  Namibia,  South Africa', 'symbol':'R'},
'ZMW': {'countries': 'Zambia', 'symbol':'K'},
'ZWL': {'countries': 'Zimbabwe', 'symbol':'$'},
'CNH':{'countries':'China - Offshore Hongkong','symbol':'元 / ¥'},
'CNT':{'countries':'China - Offshore Taiwan','symbol':'元 / ¥'},
'GGP':{'countries':'Guernsey','symbol':'£'},
'IMP':{'countries':'Isle of Man','symbol':'£'},
'JEP':{'countries':'Jersey','symbol':'£'},
'KID':{'countries':'Kiribati','symbol':'$'},
'PRB':{'countries':'Transnistria','symbol':'руб/р'},
'SLS':{'countries':'Somaliland','symbol':'Sl. Sh'},
'TVD':{'countries':'Tuvalu','symbol':'$ ($T, TV$)'},
'ZWB':{'countries':'Zimbabwe','symbol':'$'},
'ADF':{'countries':'Andorra','symbol':'F or Fr'},
'ARL':{'countries':'Argentina','symbol':'$L'},
'MAF':{'countries':'Morroco','symbol':''},
'MCF':{'countries':'Monaco','symbol':'fr. or F'},
'MKN':{'countries':'North Macedonia','symbol':'den / ден'},
'SML':{'countries':'San Marino','symbol':'₤, £ or L'},
'VAL':{'countries':'Vatican City','symbol':'₤, £ or L'},
'YUG':{'countries':'Yugoslavia','symbol':'din. and дин.'},
'YUO':{'countries':'Yugoslavia','symbol':'din. and дин.'},
'YUR':{'countries':'Yugoslavia','symbol':'din. and дин.'},
'ADP':{'countries':'Spain, Andorra','symbol':'Pta (plural Ptas), or ₧'},
'AFA':{'countries':'Afghanistan', 'symbol':'؋'},
'ALK':{'countries':'Albania','symbol':'L'},
'AOK':{'countries':'Angola','symbol':'Kz'},
'AON':{'countries':'Angola','symbol':'Kz'},
'AOR':{'countries':'Angola','symbol':'Kz'},
'ARA':{'countries':'Argentina','symbol':'₳'},
'ARP':{'countries':'Argentina','symbol':'$a'},
'ARY':{'countries':'Argentina','symbol':'$'},
'ATS':{'countries':'Austria','symbol':'S or öS'},
'AYM':{'countries':'Azerbaijan','symbol':'₼'},
'AZM':{'countries':'Azerbaijan','symbol':'₼'},
'BAD':{'countries':'Bosnia and Herzegovina','symbol':'BAD'},
'BEC':{'countries':'','symbol':''},
'BEF':{'countries':'Belgium','symbol':'fr.'},
'BEL':{'countries':'','symbol':''},
'BGJ':{'countries':'Bulgaria','symbol':'лв.'},
'BGK':{'countries':'Bulgaria','symbol':'лв.'},
'BGL':{'countries':'Bulgaria','symbol':'лв.'},
'BOP':{'countries':'Bolivia','symbol':'b$.'},
'BRB':{'countries':'Brazil','symbol':'Cr$'},
'BRC':{'countries':'Brazil','symbol':'Cz$'},
'BRE':{'countries':'Brazil','symbol':'Cr$'},
'BRN':{'countries':'Brazil','symbol':'NCz$'},
'BRR':{'countries':'Brazil','symbol':'CR$'},
'BUK':{'countries':'Myanmar', 'symbol':'K'},
'BYB':{'countries':'Belarus','symbol':'Br'},
'BYR':{'countries':'Belarus','symbol':'Br'},
'CHC':{'countries':'','symbol':''},
'CSD':{'countries':'Serbia','symbol':'din / дин'},
'CSJ':{'countries':'Czech Republic','symbol':'Kč'},
'CSK':{'countries':'Czechoslovakia','symbol':'Kčs'},
'CYP':{'countries':'Cyprus','symbol':'£'},
'DDM':{'countries':'German Democratic Republic','symbol':'M'},
'DEM':{'countries':'Germany','symbol':'DM'},
'ECS':{'countries':'Ecuador','symbol':'S/.'},
'ECV':{'countries':'','symbol':''},
'EEK':{'countries':'Estonia','symbol':'kr'},
'ESA':{'countries':'Spain','symbol':'Pta (plural Ptas), or ₧'},
'ESB':{'countries':'Spain','symbol':'Pta (plural Ptas), or ₧'},
'ESP':{'countries':'Spain','symbol':'Pta (plural Ptas), or ₧'},
'FIM':{'countries':'Finland','symbol':'mk'},
'FRF':{'countries':'France','symbol':'F or Fr'},
'GEK':{'countries':'Georgia','symbol':'₾ (Sign of Georgian Lari.svg), ლ, GE'},
'GHC':{'countries': 'Ghana', 'symbol':'GH₵ (Also often GH¢)'},
'GHP':{'countries': 'Ghana', 'symbol':'GH₵ (Also often GH¢)'},
'GNE':{'countries':'Guinea','symbol':''},
'GNS':{'countries':'Guinea','symbol':''},
'GQE':{'countries':'Equatorial Guinea','symbol':''},
'GRD':{'countries':'Greece','symbol':'Δρχ., Δρ. or ₯'},
'GWE':{'countries':'Portuguese Guinea','symbol':''},
'GWP':{'countries':'Guinea-Bissau','symbol':''},
'HRD':{'countries':'Croatia','symbol':''},
'IEP':{'countries':'Ireland','symbol':'£'},
'ILP':{'countries':'Israel','symbol':'ל"י‎ or I£'},
'ILR':{'countries':'Israel','symbol':'IS'},
'ISJ':{'countries':'Iceland','symbol':'	kr'},
'ITL':{'countries':'Italy','symbol':'₤'},
'LAJ':{'countries':'Lao People\'s Democratic Republic','symbol':'₭ or ₭N'},
'LSM':{'countries':'Lesotho','symbol':'L or M'},
'LTL':{'countries':'Lithuania','symbol':'Lt'},
'LTT':{'countries':'Lithuania','symbol':''},
'LUC':{'countries':'','symbol':''},
'LUF':{'countries':'Luxembourg','symbol':'F'},
'LUL':{'countries':'','symbol':''},
'LVL':{'countries':'Latvia','symbol':'Ls'},
'LVR':{'countries':'','symbol':''},
'MGF':{'countries':'Madagascar','symbol':'MF'},
'MLF':{'countries':'Mali','symbol':'MAF'},
'MRO':{'countries':'Mauritania','symbol':'UM'},
'MTL':{'countries':'Malta','symbol':'₤ and Lm'},
'MTP':{'countries':'Malta','symbol':'₤ and Lm'},
'MVQ':{'countries':'Maldivas','symbol':'Rf, MRf, MVR, .ރ or /-'},
'MXP':{'countries':'Mexico','symbol':'$ or Mex$'},
'MZE':{'countries':'Mozambique','symbol':'?'},
'MZM':{'countries':'Mozambique','symbol':'MT, MTn'},
'NIC':{'countries':'Nicaragua','symbol':'C$'},
'NLG':{'countries':'Netherlands','symbol':'ƒ or fl.'},
'PEH':{'countries':'Peru','symbol':'S/.'},
'PEI':{'countries':'Peru','symbol':'I/.'},
'PES':{'countries':'Peru','symbol':'S/.'},
'PLZ':{'countries':'Poland','symbol':'zł'},
'PTE':{'countries':'Portugal','symbol':'$'},
'RHD':{'countries':'Rhodesia','symbol':'$'},
'ROK':{'countries':'Romania', 'symbol':'L'},
'ROL':{'countries':'Romania', 'symbol':'L'},
'RUR':{'countries':'Russia','symbol':'₽'},
'SDD':{'countries':'Sudan','symbol':'LSd or £Sd'},
'SDP':{'countries':'Sudan','symbol':'SDG, £SD or ج.س'},
'SIT':{'countries':'Slovenia','symbol':''},
'SKK':{'countries':'Slovakia','symbol':'Sk'},
'SRG':{'countries':'Suriname','symbol':'ƒ or fl'},
'STD':{'countries':'São Tomé and Príncipe','symbol':'Db'},
'SUR':{'countries':'Soviet Union','symbol':'руб'},
'TJR':{'countries':'Tajikistan','symbol':''},
'TMM':{'countries':'Turkmenistan','symbol':'T'},
'TPE':{'countries':'Portuguese Timor','symbol':''},
'TRL':{'countries':'Turkey','symbol':'₺, TL'},
'UAK':{'countries':'Ukrainian People\'s Republic','symbol':''},
'UGS':{'countries':'Uganda','symbol':'USh'},
'USS':{'countries':'United States of America','symbol':''},
'UYN':{'countries':'Uruguay','symbol':'$ or $U'},
'UYP':{'countries':'Uruguay','symbol':'$ or $U'},
'VEF':{'countries':'Venezuela', 'symbol':'Bs.S. or Bs'},
'VEB':{'countries':'Venezuela', 'symbol':'Bs.S. or Bs'},
'VNC':{'countries':'Vietnam','symbol':'₫/đ'},
'XEU':{'countries':'European Union ','symbol':'₠'},
'XFO':{'countries':'','symbol':''},
'XFU':{'countries':'','symbol':''},
'XRE':{'countries':'','symbol':''},
'YDD':{'countries':'Yemen','symbol':''},
'YUM':{'countries':'Yugoslavia','symbol':'din. and дин.'},
'YUN':{'countries':'Yugoslavia','symbol':'din. and дин.'},
'YUD':{'countries':'Yugoslavia','symbol':'din. and дин.'},
'ZAL':{'countries':'South Africa','symbol':''},
'ZMK':{'countries':'Zambia','symbol':'K'},
'ZRN':{'countries':'Democratic Republic of the Congo','symbol':''},
'ZRZ':{'countries':'Democratic Republic of the Congo','symbol':''},
'ZWC':{'countries':'Rhodesia','symbol':'$'},
'ZWD':{'countries':'Zimbabwe','symbol':'$'},
'ZWN':{'countries':'Zimbabwe','symbol':'$'},
'ZWR':{'countries':'Zimbabwe','symbol':'$'}
}